# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_auto_20160331_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
